name: Publish Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/*
      - '**.md'
      - docs/**
      - Images/readme/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Build
        run: |
          dotnet publish 'Flow.Launcher.Plugin.Caffeine.csproj' -r win-x64 --no-self-contained -c Release -o "Caffeine-${{steps.version.outputs.prop}}"
          7z a -tzip "Caffeine-${{steps.version.outputs.prop}}.zip" "./Caffeine-${{steps.version.outputs.prop}}/*"
          rm -r "Caffeine-${{steps.version.outputs.prop}}"
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "Caffeine*.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
